export enum ExpenseSchedule {
    DAILY = "DAILY",
    WEEKLY = "WEEKLY",
    BIMONTHLY = "BIMONTHLY",
    MONTHLY = "MONTHLY",
    BIMESTRIAL = "BIMESTRIAL",
    QUARTERLY = "QUARTERLY",
    BIANNUAL = "BIANNUAL",
    ANNUAL = "ANNUAL",
}
