export enum ExpenseSchedule {
    UNDEFINED = "UNDEFINED",
    DAILY = "DAILY",
    WEEKLY = "WEEKLY",
    SEMI_MONTHLY = "SEMI_MONTHLY",
    MONTHLY = "MONTHLY",
    BIMESTRIAL = "BIMESTRIAL",
    QUARTERLY = "QUARTERLY",
    BIANNUAL = "BIANNUAL",
    ANNUAL = "ANNUAL",
}
