export enum PaymentMethod {
    UNDEFINED = "UNDEFINED",
    BANK_CARD = "BANK_CARD",
    CASH = "CASH",
    CHECK = "CHECK",
    BANK_TRANSFER = "BANK_TRANSFER",
    CRYPTO_CURRENCY = "CRYPTO_CURRENCY",
}
